clc;
clear all;
close all;
a = imread('C:\Users\ashwi\Desktop\squidward.png');
b = rgb2gray(a);
subplot(2,2,1);
imshow(b);
title('grayscale image of original rgb image');
c = im2double(b);
subplot(2,2,2);
imhist(c);
title('histogram mapping of grayscale original image');
d = histeq (c);
subplot(2,2,3);
imshow(d);
title('grayscale original image after histogram equalisation');
subplot(2,2,4);
imhist(d);
title('histogram mapping of equalised grayscale original image');